version: '3'
services:
  zoo-node:
    image: zookeeper:3.6.2
    container_name: zoo-node
    hostname: zoo-node
    ports:
      - "2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo-node:2888:3888;2181
  node-1:
    image: nads95/nifi:1.14.0
    container_name: node-1
    ports:
      - "8443:8443"
    environment:
      NIFI_WEB_HTTPS_PORT: 8443
      NIFI_WEB_HTTPS_HOST: node-1
      NIFI_SENSITIVE_PROPS_KEY: awesome_nifi
      AUTH: tls
      KEYSTORE_PATH: /opt/nifi/nifi-current/certs/keystore.jks
      KEYSTORE_TYPE: jks
      KEYSTORE_PASSWORD: eU5dA1mkmicAi6LaUgj6BiiXpHoh2l3EZ2SId5EmNCM
      KEY_PASSWORD: eU5dA1mkmicAi6LaUgj6BiiXpHoh2l3EZ2SId5EmNCM
      TRUSTSTORE_PATH: /opt/nifi/nifi-current/certs/truststore.jks
      TRUSTSTORE_PASSWORD: N0JKy78/Uv971N3T0WMIDxOFqea9QL7LEtHJOKIvWJk
      TRUSTSTORE_TYPE: jks
      NIFI_AUTHORIZER_CONF_FILE: /opt/nifi/nifi-current/authorizers.xml
      NIFI_SECURITY_USER_AUTHORIZER: managed-authorizer
      INITIAL_ADMIN_IDENTITY: 'CN=nadeem, OU=NIFI'
      NIFI_ZK_CONNECT_STRING: zoo-node:2181
      NIFI_CLUSTER_IS_NODE: 'true'
      NIFI_CLUSTER_ADDRESS: node-1
      NIFI_CLUSTER_NODE_PROTOCOL_PORT: 9998
      NIFI_ELECTION_MAX_WAIT: 1 min
    volumes:
      - ./node-1/certs:/opt/nifi/nifi-current/certs
      - ./authorizers.xml:/opt/nifi/nifi-current/authorizers.xml
  node-2:
    image: nads95/nifi:1.14.0
    container_name: node-2
    ports:
      - "8444:8443"
    environment:
      NIFI_WEB_HTTPS_PORT: 8443
      NIFI_WEB_HTTPS_HOST: node-2
      NIFI_SENSITIVE_PROPS_KEY: awesome_nifi
      AUTH: tls
      KEYSTORE_PATH: /opt/nifi/nifi-current/certs/keystore.jks
      KEYSTORE_TYPE: jks
      KEYSTORE_PASSWORD: Gux5aZZHYmoEwQfjxo0Yop31gUvi+1FSLfpcakxKBGI
      KEY_PASSWORD: Gux5aZZHYmoEwQfjxo0Yop31gUvi+1FSLfpcakxKBGI
      TRUSTSTORE_PATH: /opt/nifi/nifi-current/certs/truststore.jks
      TRUSTSTORE_PASSWORD: QloPLFouiHi+XZYpJYwNeJP1mp5d0sXqsARa/vRJQSE
      TRUSTSTORE_TYPE: jks
      NIFI_AUTHORIZER_CONF_FILE: /opt/nifi/nifi-current/authorizers.xml
      NIFI_SECURITY_USER_AUTHORIZER: managed-authorizer
      INITIAL_ADMIN_IDENTITY: 'CN=nadeem, OU=NIFI'
      NIFI_ZK_CONNECT_STRING: zoo-node:2181
      NIFI_CLUSTER_IS_NODE: 'true'
      NIFI_CLUSTER_ADDRESS: node-2
      NIFI_CLUSTER_NODE_PROTOCOL_PORT: 9998
      NIFI_ELECTION_MAX_WAIT: 1 min
    volumes:
      - ./node-2/certs:/opt/nifi/nifi-current/certs
      - ./authorizers.xml:/opt/nifi/nifi-current/authorizers.xml
